[build-system]
    requires = ["setuptools>=68", "wheel"]
    build-backend = "setuptools.build_meta"


[project]
    name = "ndnc"
    version = "0.0.6"
    description = "A DSL interpreter for transparent distributed execution over NDN"
    authors = [{ name = "tryuuu", email = "ryu23210@gmail.com" }]
    readme = "README.pypi.md"
    license = "MIT"
    license-files = ["LICENSE"]
    requires-python = ">=3.10"
    dependencies = [
        "lark==1.1.9",
        "python-ndn"
    ]
    keywords = ["ndn", "dsl", "distributed", "icn"]
    classifiers = [
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Interpreters",
    ]

[project.urls]
    Homepage = "https://github.com/tryuuu/ndn-compiler"
    Repository = "https://github.com/tryuuu/ndn-compiler"

[project.scripts]
    ndnc = "ndnc.cli:main"

[tool.setuptools.package-data]
"ndnc.parser" = ["*.lark"]